use_frameworks!

target 'PBRevealViewController_Example' do
  pod 'PBRevealViewController', :path => '../'

end

target 'PBRevealViewController_Tests' do
    pod 'PBRevealViewController', :path => '../'

end
