#use_frameworks!
platform :ios, '9.0'

workspace 'PBRevealViewController.xcworkspace'

target 'PBRevealViewController_Example' do
  pod 'PBRevealViewController', :path => '../'

end

target 'Example2' do
    project '../Example2/Example2'
    pod 'PBRevealViewController', :path => '../'
    
end

target 'Example3Swift' do
    project '../Example3Swift/Example3Swift'
    pod 'PBRevealViewController', :path => '../'
    
end

target 'Example4Swift' do
    project '../Example4Swift/Example4Swift'
    pod 'PBRevealViewController', :path => '../'
    
end

target 'ExampleFortvOS' do
    project '../ExampleFortvOS/ExampleFortvOS'
    pod 'PBRevealViewController', :path => '../'
    
end
